### ISSUE TITLE
Error when generating a PDF

### ISSUE THREAD

**Issue by Haynesy** [watergis/mapbox-gl-export#39]
**Describe the bug**
Unable to generate a PDF just get a spinning wheel

**To Reproduce**
Click print icon with A3 Portrait PDF 96 DPI, 

**Expected behavior**
A PDF is generated.

**Screenshots**
![image](https://user-images.githubusercontent.com/102755/178909987-348917b6-142c-4252-923b-89edba49496a.png)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser: Chrome
 - Version: 103

**Additional context**
We are generating many layers behind the scenes using various plugins and some generated layers ourselves.
Is this something we need to fix or something the plugin can handle?

Error text:
```
mapbox-gl.js:31 Error: layers[140].type: expected one of [fill, line, symbol, circle, heatmap, fill-extrusion, raster, hillshade, background], "sky" found
    at Object.Bn [as emitValidationErrors] (mapbox-gl.js:31:133534)
    at Ue (mapbox-gl.js:35:112388)
    at i._load (mapbox-gl.js:35:114931)
    at mapbox-gl.js:35:114750
    at timer (zone.js:2405:1)
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25595:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at invokeTask (zone.js:487:1)```

**Comment by Haynesy** [comment]
Going to see if I can somehow find out which layers are missing the type.

**Comment by Haynesy** [comment]
Ah ok my bad 'sky' isn't a valid type.
